name: Winlator

on:
  workflow_dispatch: # Trigger manually only

jobs:
  apk-download-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Set app name
      run: echo "APP_NAME=Winlator_9.0" >> $GITHUB_ENV


    - name: Download APK File
      run: |
        # Create necessary folders
        mkdir -p apks/emulator/winlator

        # Download the APK file
        curl -L -o apks/emulator/winlator/${{ env.APP_NAME }}.apk "https://github.com/brunodev85/winlator/releases/download/v9.0.0/Winlator_9.0.apk"

    - name: Download Image
      run: |
        # Download image from the internet
        curl -L -o apks/emulator/winlator/${{ env.APP_NAME }}.png "https://img.utdstc.com/icon/49d/ef9/49def94f7629f13a7d62815cd7c166ebac0613ce57cf497e99179c01a1c2b5c7:200"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "${{ env.APP_NAME }}" # Adjust if needed
        release_name: "${{ env.APP_NAME }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: apks/emulator/winlator/${{ env.APP_NAME }}.apk
        asset_name: ${{ env.APP_NAME }}.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Image to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: apks/emulator/winlator/${{ env.APP_NAME }}.png
        asset_name: ${{ env.APP_NAME }}.png
        asset_content_type: image/png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Release Description with Image
      run: |
        # Update release description with image link
        IMAGE_URL="https://github.com/${{ github.repository }}/releases/download/winlator-9.0/winlator-image.jpg"
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"${{ env.APP_NAME }} release. ![$IMAGE_URL]($IMAGE_URL)\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}
